### ISSUE TITLE
totally changed images with shallowest encoder

### ISSUE THREAD

**Issue by Equationliu** [qqqlingx/FeatureSpaceAttack#2]
> We employ targeted attack on Imagenet Resnet50 v1 Model. We report the successful rate and corresponding human preference rate under different bound. We choose Imagenet and decoder=1 for this experiment.

However, I got totally changed images (only edges) after runining

```
python -u attack.py --bound 1.5 --dataset=imagenet --decoder=1 --model=imagenet_normal
```

![edges.png](https://i.loli.net/2021/08/08/lh5SGa6TePFkQWO.jpg)

**Comment by qiulingxu** [comment]
Hello, in order to reproduce the bug, have you changed anything, especially the preprocessing part? Did you use the latest version as well?

**Comment by Equationliu** [comment]
> Hello, in order to reproduce the bug, have you changed anything, especially the preprocessing part? Did you use the latest version as well?

I only changed the `x_batch, y_batch = get_data()` to my own dataloader which read images (0-255) in RGB format.

It seems to work well when decoder=2 or 3.

**Comment by qiulingxu** [comment]
> 
> 
> > Hello, in order to reproduce the bug, have you changed anything, especially the preprocessing part? Did you use the latest version as well?
> 
> I only changed the `x_batch, y_batch = get_data()` to my own dataloader which read images (0-255) in RGB format.
> 
> It seems to work well when decoder=2 or 3.

Hello, thanks for your patience. I checked the code. It seems that the provided pre-trained model is mismatched with the current setting. As a quick solution, one can train the shallow decoder. I will update the corresponding model in few days.

**Comment by qiulingxu** [comment]
Hello, I have updated the decoder. Please download it again. And let me know if there is any problem.
Test on shallowest
![0](https://user-images.githubusercontent.com/25995542/130804061-32653922-ad2e-4fd7-bb39-61733a000730.jpg)

**Comment by Equationliu** [comment]
Have you updated the decoder?

I download the pre-trained decoders and get files that were generated in 2020.

![shallowesttransform.png](https://i.loli.net/2021/08/25/17WoXb2KGsZrADn.png)

**Comment by qiulingxu** [comment]
Yes, the files are updated. Please double check the shallowest model for imagenet.
